name: Discord Bot Running

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行 6時間なのはgithub Actionsのジョブ時間制限が6時間だから

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Create Cookie File
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > youtube.cookies
          chmod 600 youtube.cookies
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg

          # タイムゾーンを日本時間に設定
      - name: Set timezone to JST
        run: |
          sudo timedatectl set-timezone Asia/Tokyo

          # Torをインストール
      - name: Install Tor
        run: |
          ```bash
          sudo apt-get update
          ```
          ```bash
          sudo apt-get install -y tor
          ```
          ```bash
          sudo service tor start
          ```

          # Torを日本のexit nodeに設定
      - name: Configure Tor for JP exit nodes
        run: |
          echo "ExitNodes {jp}" | sudo tee -a /etc/tor/torrc
          echo "StrictNodes 1" | sudo tee -a /etc/tor/torrc
          ```bash
          sudo service tor restart
          ```

      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          PROXY: 'socks5://127.0.0.1:9050'

        run: python main.py
