name: Discord Bot Running

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行 6時間なのはgithub Actionsのジョブ時間制限が6時間だから

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Create Cookie File
        run: |
          printf "%s" "${{ secrets.YOUTUBE_COOKIES }}" > youtube.cookies
          chmod 600 youtube.cookies  # セキュリティ設定を追加

      - name: Debug Cookie File
        run: |
          ls -lah youtube.cookies  # クッキーファイルが作成されているか確認
          head -n 5 youtube.cookies  # クッキーの最初の5行を表示（重要な情報は漏れないように）
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python main.py
