name: Discord Bot Running

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行 6時間なのはgithub Actionsのジョブ時間制限が6時間だから

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Create Cookie File
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > youtube.cookies
          chmod 600 youtube.cookies
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg

      #WARPの導入
      - name: Install Cloudflare WARP
        run: |
          curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt update
          sudo apt install cloudflare-warp

      - name: Check proxy commands
        run: |
          warp-cli proxy --help

      #5秒のスリープでWARPの起動待ち
      - name: Start WARP daemon
        run: |
          sudo systemctl start warp-svc
          sleep 5

      #WARPの起動とSOCKS5プロキシモードで起動
      - name: Start WARP in SOCKS proxy mode
        run: |
          warp-cli --accept-tos registration new
          warp-cli --accept-tos mode proxy
          warp-cli --accept-tos connect
          sleep 10
          warp-cli --accept-tos tunnel endpoint set 162.159.192.1:2408
          sleep 10
          warp-cli --accept-tos status

      - name: Verify WARP connection
        run: |
          curl -v -x "socks5://127.0.0.1:40000" https://www.cloudflare.com/cdn-cgi/trace/

      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

        run: python main.py
