name: Discord Bot Running

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行 6時間なのはgithub Actionsのジョブ時間制限が6時間だから

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Create Cookie File
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > youtube.cookies
          chmod 600 youtube.cookies
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg

      #WARPの導入
      - name: Install Cloudflare WARP
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo tee /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/jammy main" | sudo tee /etc/apt/sources.list.d/cloudflare-warp.list
          cat /etc/apt/sources.list.d/cloudflare-warp.list
          sudo apt update && sudo apt install -y cloudflare-warp

      #WARPの起動とSOCKS5プロキシモードで起動
      - name: Start Cloudflare WARP Proxy
        run: |
          warp-cli register
          warp-cli connect
          warp-cli set-mode proxy
          warp-cli set-proxy-port 40000
          warp-cli enable-always-on

      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

        run: python main.py
